services:
  postgres:
    env_file: .env.production
    restart: always
  linkpool:
    env_file: .env.production
    restart: always
    ports: !override
      - "127.0.0.1:3000:3000"
  meilisearch:
    env_file: .env.production
    restart: always
