services:
  postgres:
    env_file: .env.production
    restart: always
  linkpool:
    env_file: .env.production
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
  meilisearch:
    env_file: .env.production
    restart: always
