services:
  linkpool:
    image: ghcr.io/dminhpl/linkpool:latest

    env_file:
      - .env.production

    environment:
      DATABASE_URL: ${DATABASE_URL}

    restart: always

  meilisearch:
    env_file:
      - .env.production

    restart: always